# Generated by Django 3.0.3 on 2020-03-06 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20200305_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
    ]
