# Generated by Django 3.0.3 on 2020-03-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_remove_game_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='story',
            field=models.CharField(default='Story:', max_length=1000),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.CharField(blank=True, editable=False, help_text='Unique URL path to access this page. Generated by the system.', max_length=10),
        ),
    ]
