# Generated by Django 3.0.3 on 2020-03-06 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20200306_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='story',
        ),
    ]
